#ifndef _BS_VM_BUILTINS_H_
#define _BS_VM_BUILTINS_H_

#include "common.h"
#include "vm.h"

// ===[ Built-in Variable ID Enum ]===
typedef enum {
    BUILTIN_VAR_UNKNOWN = -1,

    // Instance properties
    BUILTIN_VAR_X,
    BUILTIN_VAR_Y,
    BUILTIN_VAR_XPREVIOUS,
    BUILTIN_VAR_YPREVIOUS,
    BUILTIN_VAR_XSTART,
    BUILTIN_VAR_YSTART,
    BUILTIN_VAR_IMAGE_SPEED,
    BUILTIN_VAR_IMAGE_INDEX,
    BUILTIN_VAR_IMAGE_XSCALE,
    BUILTIN_VAR_IMAGE_YSCALE,
    BUILTIN_VAR_IMAGE_ANGLE,
    BUILTIN_VAR_IMAGE_ALPHA,
    BUILTIN_VAR_IMAGE_BLEND,
    BUILTIN_VAR_IMAGE_NUMBER,
    BUILTIN_VAR_IMAGE_SINGLE,
    BUILTIN_VAR_SPRITE_INDEX,
    BUILTIN_VAR_SPRITE_WIDTH,
    BUILTIN_VAR_SPRITE_HEIGHT,
    BUILTIN_VAR_SPRITE_XOFFSET,
    BUILTIN_VAR_SPRITE_YOFFSET,
    BUILTIN_VAR_BBOX_LEFT,
    BUILTIN_VAR_BBOX_RIGHT,
    BUILTIN_VAR_BBOX_TOP,
    BUILTIN_VAR_BBOX_BOTTOM,
    BUILTIN_VAR_BROWSER_WIDTH,
    BUILTIN_VAR_BROWSER_HEIGHT,
    BUILTIN_VAR_VISIBLE,
    BUILTIN_VAR_DEPTH,
    BUILTIN_VAR_PERSISTENT,
    BUILTIN_VAR_SOLID,
    BUILTIN_VAR_MASK_INDEX,
    BUILTIN_VAR_LAYER,
    BUILTIN_VAR_ID,
    BUILTIN_VAR_OBJECT_INDEX,
    BUILTIN_VAR_SPEED,
    BUILTIN_VAR_DIRECTION,
    BUILTIN_VAR_HSPEED,
    BUILTIN_VAR_VSPEED,
    BUILTIN_VAR_FRICTION,
    BUILTIN_VAR_GRAVITY,
    BUILTIN_VAR_GRAVITY_DIRECTION,
    BUILTIN_VAR_ALARM,

    // Path instance variables
    BUILTIN_VAR_PATH_INDEX,
    BUILTIN_VAR_PATH_POSITION,
    BUILTIN_VAR_PATH_POSITIONPREVIOUS,
    BUILTIN_VAR_PATH_SPEED,
    BUILTIN_VAR_PATH_SCALE,
    BUILTIN_VAR_PATH_ORIENTATION,
    BUILTIN_VAR_PATH_ENDACTION,

    // Timeline instance variables
    BUILTIN_VAR_TIMELINE_INDEX,
    BUILTIN_VAR_TIMELINE_POSITION,
    BUILTIN_VAR_TIMELINE_SPEED,
    BUILTIN_VAR_TIMELINE_RUNNING,
    BUILTIN_VAR_TIMELINE_LOOP,

    // Room properties
    BUILTIN_VAR_ROOM,
    BUILTIN_VAR_ROOM_FIRST,
    BUILTIN_VAR_ROOM_LAST,
    BUILTIN_VAR_ROOM_SPEED,
    BUILTIN_VAR_ROOM_WIDTH,
    BUILTIN_VAR_ROOM_HEIGHT,
    BUILTIN_VAR_ROOM_PERSISTENT,

    // View properties
    BUILTIN_VAR_VIEW_CURRENT,
    BUILTIN_VAR_VIEW_ENABLED,
    BUILTIN_VAR_CAMERA_VIEW,
    BUILTIN_VAR_VIEW_XVIEW,
    BUILTIN_VAR_VIEW_YVIEW,
    BUILTIN_VAR_VIEW_WVIEW,
    BUILTIN_VAR_VIEW_HVIEW,
    BUILTIN_VAR_VIEW_XPORT,
    BUILTIN_VAR_VIEW_YPORT,
    BUILTIN_VAR_VIEW_WPORT,
    BUILTIN_VAR_VIEW_HPORT,
    BUILTIN_VAR_VIEW_VISIBLE,
    BUILTIN_VAR_VIEW_ANGLE,
    BUILTIN_VAR_VIEW_HBORDER,
    BUILTIN_VAR_VIEW_VBORDER,
    BUILTIN_VAR_VIEW_OBJECT,
    BUILTIN_VAR_VIEW_HSPEED,
    BUILTIN_VAR_VIEW_VSPEED,
    BUILTIN_VAR_VIEW_SURFACE_ID,

    // Background properties
    BUILTIN_VAR_BACKGROUND_VISIBLE,
    BUILTIN_VAR_BACKGROUND_INDEX,
    BUILTIN_VAR_BACKGROUND_X,
    BUILTIN_VAR_BACKGROUND_Y,
    BUILTIN_VAR_BACKGROUND_XSCALE,
    BUILTIN_VAR_BACKGROUND_YSCALE,
    BUILTIN_VAR_BACKGROUND_HSPEED,
    BUILTIN_VAR_BACKGROUND_VSPEED,
    BUILTIN_VAR_BACKGROUND_WIDTH,
    BUILTIN_VAR_BACKGROUND_HEIGHT,
    BUILTIN_VAR_BACKGROUND_ALPHA,
    BUILTIN_VAR_BACKGROUND_COLOR,
    BUILTIN_VAR_BACKGROUND_COLOUR,

    // OS constants
    BUILTIN_VAR_OS_TYPE,
    BUILTIN_VAR_OS_UNKNOWN,
    BUILTIN_VAR_OS_WIN32,
    BUILTIN_VAR_OS_WINDOWS,
    BUILTIN_VAR_OS_MACOSX,
    BUILTIN_VAR_OS_PSP,
    BUILTIN_VAR_OS_IOS,
    BUILTIN_VAR_OS_ANDROID,
    BUILTIN_VAR_OS_SYMBIAN,
    BUILTIN_VAR_OS_LINUX,
    BUILTIN_VAR_OS_WINPHONE,
    BUILTIN_VAR_OS_TIZEN,
    BUILTIN_VAR_OS_WIN8NATIVE,
    BUILTIN_VAR_OS_WIIU,
    BUILTIN_VAR_OS_3DS,
    BUILTIN_VAR_OS_PSVITA,
    BUILTIN_VAR_OS_BB10,
    BUILTIN_VAR_OS_PS4,
    BUILTIN_VAR_OS_XBOXONE,
    BUILTIN_VAR_OS_PS3,
    BUILTIN_VAR_OS_XBOX360,
    BUILTIN_VAR_OS_UWP,
    BUILTIN_VAR_OS_AMAZON,
    BUILTIN_VAR_OS_SWITCH,
    BUILTIN_VAR_OS_LLVM_WIN32,
    BUILTIN_VAR_OS_LLVM_MACOSX,
    BUILTIN_VAR_OS_LLVM_PSP,
    BUILTIN_VAR_OS_LLVM_IOS,
    BUILTIN_VAR_OS_LLVM_ANDROID,
    BUILTIN_VAR_OS_LLVM_SYMBIAN,
    BUILTIN_VAR_OS_LLVM_LINUX,
    BUILTIN_VAR_OS_LLVM_WINPHONE,

    // Timing
    BUILTIN_VAR_CURRENT_DAY,
    BUILTIN_VAR_CURRENT_HOUR,
    BUILTIN_VAR_CURRENT_MINUTE,
    BUILTIN_VAR_CURRENT_MONTH,
    BUILTIN_VAR_CURRENT_SECOND,
    BUILTIN_VAR_CURRENT_TIME,
    BUILTIN_VAR_CURRENT_WEEKDAY,
    BUILTIN_VAR_CURRENT_YEAR,

    // File system
    BUILTIN_VAR_WORKING_DIRECTORY,

    // Arguments
    BUILTIN_VAR_ARGUMENT_COUNT,
    BUILTIN_VAR_ARGUMENT,
    BUILTIN_VAR_ARGUMENT0,
    BUILTIN_VAR_ARGUMENT1,
    BUILTIN_VAR_ARGUMENT2,
    BUILTIN_VAR_ARGUMENT3,
    BUILTIN_VAR_ARGUMENT4,
    BUILTIN_VAR_ARGUMENT5,
    BUILTIN_VAR_ARGUMENT6,
    BUILTIN_VAR_ARGUMENT7,
    BUILTIN_VAR_ARGUMENT8,
    BUILTIN_VAR_ARGUMENT9,
    BUILTIN_VAR_ARGUMENT10,
    BUILTIN_VAR_ARGUMENT11,
    BUILTIN_VAR_ARGUMENT12,
    BUILTIN_VAR_ARGUMENT13,
    BUILTIN_VAR_ARGUMENT14,
    BUILTIN_VAR_ARGUMENT15,

    // Keyboard
    BUILTIN_VAR_KEYBOARD_KEY,
    BUILTIN_VAR_KEYBOARD_LASTCHAR,
    BUILTIN_VAR_KEYBOARD_LASTKEY,
    BUILTIN_VAR_KEYBOARD_STRING,

    // Mouse
    BUILTIN_VAR_MOUSE_X,
    BUILTIN_VAR_MOUSE_Y,
    BUILTIN_VAR_MOUSE_BUTTON,
    BUILTIN_VAR_MOUSE_LASTBUTTON,
    BUILTIN_VAR_CURSOR_SPRITE,

    // Surfaces
    BUILTIN_VAR_APPLICATION_SURFACE,

    // Constants
    BUILTIN_VAR_TRUE,
    BUILTIN_VAR_FALSE,
    BUILTIN_VAR_INFINITY,
    BUILTIN_VAR_PI,
    BUILTIN_VAR_UNDEFINED,

    // Path action constants
    BUILTIN_VAR_PATH_ACTION_STOP,
    BUILTIN_VAR_PATH_ACTION_RESTART,
    BUILTIN_VAR_PATH_ACTION_CONTINUE,
    BUILTIN_VAR_PATH_ACTION_REVERSE,

    // Buffer type constants
    BUILTIN_VAR_BUFFER_FIXED,
    BUILTIN_VAR_BUFFER_GROW,
    BUILTIN_VAR_BUFFER_WRAP,
    BUILTIN_VAR_BUFFER_FAST,

    // Buffer data type constants
    BUILTIN_VAR_BUFFER_U8,
    BUILTIN_VAR_BUFFER_S8,
    BUILTIN_VAR_BUFFER_U16,
    BUILTIN_VAR_BUFFER_S16,
    BUILTIN_VAR_BUFFER_U32,
    BUILTIN_VAR_BUFFER_S32,
    BUILTIN_VAR_BUFFER_F16,
    BUILTIN_VAR_BUFFER_F32,
    BUILTIN_VAR_BUFFER_F64,
    BUILTIN_VAR_BUFFER_BOOL,
    BUILTIN_VAR_BUFFER_STRING,
    BUILTIN_VAR_BUFFER_U64,
    BUILTIN_VAR_BUFFER_TEXT,

    // Buffer seek mode constants
    BUILTIN_VAR_BUFFER_SEEK_START,
    BUILTIN_VAR_BUFFER_SEEK_RELATIVE,
    BUILTIN_VAR_BUFFER_SEEK_END,

    // Other
    BUILTIN_VAR_INSTANCE_COUNT,
    BUILTIN_VAR_INSTANCE_ID,
    BUILTIN_VAR_FPS,
    BUILTIN_VAR_FPS_REAL,
    BUILTIN_VAR_DEBUG_MODE,
    BUILTIN_VAR_DELTA_TIME,

    // Legacy GMS 1.x globals
    BUILTIN_VAR_SCORE,
    BUILTIN_VAR_LIVES,
    BUILTIN_VAR_HEALTH,

    // Gamepad constants
    BUILTIN_VAR_GP_FACE1,
    BUILTIN_VAR_GP_FACE2,
    BUILTIN_VAR_GP_FACE3,
    BUILTIN_VAR_GP_FACE4,
    BUILTIN_VAR_GP_SHOULDERL,
    BUILTIN_VAR_GP_SHOULDERR,
    BUILTIN_VAR_GP_SHOULDERLB,
    BUILTIN_VAR_GP_SHOULDERRB,
    BUILTIN_VAR_GP_SELECT,
    BUILTIN_VAR_GP_START,
    BUILTIN_VAR_GP_STICKL,
    BUILTIN_VAR_GP_STICKR,
    BUILTIN_VAR_GP_PADU,
    BUILTIN_VAR_GP_PADD,
    BUILTIN_VAR_GP_PADL,
    BUILTIN_VAR_GP_PADR,
    BUILTIN_VAR_GP_HOME,
    BUILTIN_VAR_GP_AXIS_LH,
    BUILTIN_VAR_GP_AXIS_LV,
    BUILTIN_VAR_GP_AXIS_RH,
    BUILTIN_VAR_GP_AXIS_RV,

    // Async system
    BUILTIN_VAR_ASYNC_LOAD,
    BUILTIN_VAR_EVENT_DATA,
} BuiltinVarId;

void VMBuiltins_registerAll(VMContext* ctx);
int16_t VMBuiltins_resolveBuiltinVarId(const char* name);
bool VMBuiltins_isInstanceScopedBuiltinVar(int16_t builtinVarId);
// Asserts at startup that the internal builtin-var lookup table is strictly sorted by strcmp order (required for bsearch) and has no duplicates.
void VMBuiltins_checkIfBuiltinVarTableIsSorted(void);
RValue VMBuiltins_getVariable(VMContext* ctx, Instance* inst, int16_t builtinVarId, const char* name, int32_t arrayIndex);
void VMBuiltins_setVariable(VMContext* ctx, Instance* inst, int16_t builtinVarId, const char* name, RValue val, int32_t arrayIndex);

#endif /* _BS_VM_BUILTINS_H_ */
